events { worker_connections 1024; }
http {
    upstream spring-backend {
        server spring-v1:8080 weight=9; # 트래픽 90%
        server spring-v2:8080 weight=1; # 트래픽 10%
    }
    server {
        listen 80;
        location / {
            proxy_pass http://spring-backend;
        }
    }
}