spring:
  application:
    name: test

  datasource:
    url: jdbc:mysql://mysql:3306/recommendation?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user
    password: 1234

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      # APP_VERSION이라는 환경변수가 들어오면 그 값을 쓰고, 없으면 기본값인 'v1'을 쓴다는 뜻입니다.
      version: ${APP_VERSION:v1}